### ISSUE TITLE
Build fails due to ota.here.com being down

### ISSUE THREAD

**Issue by vnd** [uptane/meta-updater#102]
aktualizr build is trying to access https://tuf-cli-releases.ota.here.com which seems to be down for at least few days if not weeks. I've tried toggling GARAGE_SIGN_AUTOVERSION but it basically just changes sub-URL, and build still fails due to fetching error either way.

What's the current state: is it discontinued or down temporarily?

**Comment by cajun-rat** [comment]
I hit this on Monday while working on Aktualizr. I believe that URL is permanently gone. I have a fix locally but didn't open a PR yet.

**Comment by cajun-rat** [comment]
That should do it https://github.com/uptane/aktualizr/pull/112  We'll still need to modify the aktualizr recipe in meta-updater

**Comment by vnd** [comment]
Thank you! Looks like with this akutalizr fix setting GARAGE_SIGN_AUTOVERSION to "1" might also fix yocto build even without meta-updater changes.
