### ISSUE TITLE
Add SELinux- secontext handling when packing the rootfs using tar utility

### ISSUE THREAD

**Issue by rsiddoji** [uptane/meta-updater#111]
Hi team ,
Current krikstone branch code when handling rootfs folder for creating ostree based rootfs folder its not considering selinux .
Following is the patch that will try to pass selinux option to tar utility .
If the rootfs is already labeled with selinux it will preserve the labels else it will be NOP (https://www.gnu.org/software/tar/manual/tar.html)
Can you please help to get this review and help us on how we can merge this change .

Attaching the single line changes
its just adding the --selinux to tar utility .

[0001-RFC-meta-updater-adding-selinux-support-for-in-packi.patch](https://github.com/user-attachments/files/16962296/0001-RFC-meta-updater-adding-selinux-support-for-in-packi.patch)
Regards,
Ravi.,

**Comment by ricardosalveti** [comment]
Please propose your patch as a pull request at https://github.com/uptane/meta-updater/pulls.

**Comment by ricardosalveti** [comment]
Merged as part of https://github.com/uptane/meta-updater/pull/113
