### ISSUE TITLE
Setting SOURCE_DATE_EPOCH to zero causes errors during the python native package builds

### ISSUE THREAD

**Issue by schoener-one** [uptane/meta-updater#96]
Problem:
Setting the environment variable **SOURCE_DATE_EPOCH** _conf/distro/sota.conf.inc_ to zero leads to python build errors for the native package builds, because the file timestamps of some packed files are set to a time before 1980. This causes the error output  'ZIP does not support timestamps before 1980' from the python _zipfile.py_ script.

Solution:
Setting the SOURCE_DATE_EPOCH time to a time after 1980 fixed my problems.

Hint:
I was using the kirkstone branch!

**Comment by pattivacek** [comment]
Hello, this is unfortunately a known issue without a completely satisfactory solution yet, see https://github.com/uptane/meta-updater/pull/35.
