### ISSUE TITLE
aktualizr-native fails to build caused by 'undefined reference' in garage-check

### ISSUE THREAD

**Issue by schoener-one** [uptane/meta-updater#97]
The aktualizr tool build from the meta-update (kirkstone) fails to build, caused by undefined references during the garage-check build. The linkage references to the boost::log are missing somehow. I tried a few things to find out the root cause but without success, and now I'm giving up. The CMake files look reasonable for me.

Have you seen such a behaviour before or do maybe know a solution for that?
[build.log.tar.gz](https://github.com/uptane/meta-updater/files/14537245/build.log.tar.gz)

**Comment by pattivacek** [comment]
Are you also building with a layer that includes boost, and are you sure the boost::log is being built and installed in the image? This looks like an issue at the Yocto level, specifically in your configuration. I can't really actively support debugging but check your layers and what's getting built.

**Comment by schoener-one** [comment]
Yes, you're right. I also think it is caused by my layer, because I removed temporarily and now it is working again. Thanks for that quick response anyway!
